### ISSUE TITLE
Error: when looking for s3

### ISSUE THREAD

**Issue by random-robbie** [emtunc/SlackPirate#38] opened 2019-04-02 13:32 UTC
When using python 3.5.2

Command

```
python3 SlackPirate.py --token xoxb-xxx
```

Output.
```
START: Attempting to find references to S3 buckets
Traceback (most recent call last):
  File "SlackPirate.py", line 831, in <module>
    scan(token=provided_token, scan_context=collected_scan_context)
  File "SlackPirate.py", line 327, in find_s3
    page_count_by_query[query] = (r['messages']['pagination']['page_count'])
KeyError: 'messages'

```

**Comment by random-robbie** [comment] 2019-04-02 13:57
Same with python 3.6 in docker.

[![Screenshot-2019-04-02-at-14-54-55.png](https://i.postimg.cc/dQGddGT7/Screenshot-2019-04-02-at-14-54-55.png)](https://postimg.cc/V5LdPrg1)

**Comment by emtunc** [comment] 2019-04-02 23:49
Hello @random-robbie ! Thanks for the issue report. This is interesting but I think I know what the problem is (ignoring the fact I'm not catching this as an exception in the code :o) - a lot of the functions use the Slack `search.messages` API which cannot be queried by a Slack bot token which I can see is what you are using. 

Not sure there is a workaround for this but will have a look when time permits.

See the `Works with` section here https://api.slack.com/methods/search.messages

**Comment by emtunc** [comment] 2020-03-27 00:26
Closing as it doesn't seem to be possible to search messages with a bot user token.

**Closed by emtunc** 2020-03-27 00:26 UTC
